### PR TITLE
Added new operator entity: 0x4A1bb298c57D0eEFfD57d7eED0Ee86923583Fa73

### PR DESCRIPTION
**Pull request by varunsh-is**
Added new operator entity: 0x4A1bb298c57D0eEFfD57d7eED0Ee86923583Fa73

 - **Name**: InfraSingularity
 - **Description**: InfraSingularity aims to radically transform the Web3 ecosystem by pioneering as an investor, and builder of institutional staking platform..
 - **Links**:
    - [Website](https://infrasingularity.com/)
    - [X](https://x.com/ISinfra)
 - **Icon**: Included (256x256 px)

### CODE REVIEW

**Comment by sergey-symbiotic** [comment]
Thank you for contribution!
Please notice that icon should be 256\*256, not 300\*300

**Comment by varunsh-is** [comment]
@sergey-symbiotic please check now

**Comment by sergey-symbiotic** [comment]
@varunsh-is now it's 250px
image
Please fix it to be 256x256

**Comment by varunsh-is** [comment]
please check now @sergey-symbiotic and let me know if any changes are required

**Pull request merged**
